### ISSUE TITLE
Is Space Ranger Cytassist supported?

### ISSUE THREAD

**Issue by pakiessling** [nf-core/spatialvi#34]
### Description of feature

Hi I was curious if this pipeline currently supports the new Space Ranger Visum FFPE analysis?
https://support.10xgenomics.com/spatial-gene-expression/software/pipelines/latest/using/count-ffpe#args

If not, consider this a feature request :)

**Comment by grst** [comment]
I believe this requires spaceranger 2.x, see also #37

**Comment by fasterius** [comment]
Closing this issue in favour of #37 .
