### ISSUE TITLE
Implement tests using nf-test

### ISSUE THREAD

**Issue by grst** [nf-core/spatialvi#36]
### Description of feature

Would be great to have the entire workflow tested, not only that it runs through, but also checking the outputs for plausibility. 

Currently the spaceranger part is not tested at all - I guess partly the challenge is to generate appropriated subsampled test data.

**Comment by fasterius** [comment]
Yes, exactly - we did think about this quite a bit, and at the moment we don't see how getting an appropriate test dataset for Space Ranger would work. Ideas are very welcome!
