### ISSUE TITLE
Update spaceranger to 2.x

### ISSUE THREAD

**Issue by grst** [nf-core/spatialvi#37]
### Description of feature

One feature that's crucial for us is that spaceranger supports CytAssist. This was added in v2.0. 

As a side, it would be great if the corresponding Dockerfiles were stored in this repo (or nf-core/modules as appropriate).

**Comment by grst** [comment]
Here's a (closed as stale) PR to modules adding spaceranger: https://github.com/nf-core/modules/pull/994
Would be good to have this in the modules repository, actually.

**Comment by fasterius** [comment]
Yes, making a Space Ranger module is something we've thought about doing, so it'll likely happen in the future. I'll see what I can do about updating the container to Space Ranger 2.0.

**Comment by grst** [comment]
I can work on creating the module, if you want. In that case it would be fab if you coulde share the Dockerfile with me as a starting point.

**Comment by fasterius** [comment]
Excellent! The Dockerfile that creates the image that is currently used is the one you're linking to in the stale PR (hosted at the nf-core DockerHub organisation).

**Comment by apeltzer** [comment]
We at nf-core at somepoint had the agreement with 10x that we can have the docker containers here at nf-core but need to make very clear (readme + docker file) that this is in no way affiliated with 10x and there is no support etc from them: 

Example at cellranger: 
https://github.com/nf-core/modules/tree/master/modules/nf-core/cellranger

**Comment by apeltzer** [comment]
> # Disclaimer: this container is not provided nor supported by Illumina or 10x Genomics.

**Comment by fasterius** [comment]
I was also in contact with them previously, but asking if one may generally create Docker images with their software (Space Ranger in this instance), are they were fine with that. Good to know that they also want the disclaimer!

**Comment by grst** [comment]
Working on it here: https://github.com/nf-core/modules/pull/3472
