### ISSUE TITLE
Aggregate samples into single object

### ISSUE THREAD

**Issue by grst** [nf-core/spatialvi#56]
### Description of feature

Would be nice to have a single object instead of inidividual h5ad files. 
Optional batch correction for integration.

**Comment by grst** [comment]
I would like to refactor a bit how AnnData objects are created and handled
 * instead of having a separate AnnData object after each step, I'd just go for two: one which has low quality spots removed and one that doesn't. Raw counts and normalized values can be stored in a single object using `adata.layers`. 
 * rely on scanpy or squidpy to read visium data (@fasterius, what was again the motivation to have a custom python script for that in the first place?)
 * merge all objects into a single AnnData object at the end, with optional export to a SpatialData object (#39). 

I'd be happy to put a PR together. 

@fasterius / @cavenel WDYT?

**Comment by fasterius** [comment]
Sounds good to me! I haven't really done any of the coding inside the reports, so don't have much to add - you'll have to ask @cavenel regarding your second point about the custom script. Might be due to legacy code from the Jackson Laboratory version of the pipeline, but that's just a guess.

**Comment by fasterius** [comment]
With the latest updates to the pipeline I think that we fulfill your first two points @grst. Regarding the third point, do you mean "merge" as in some kind of integration or just something else?

**Comment by grst** [comment]
I just mean storing all samples in a single SpatialData object rather than having one SpatialData object per sample.

**Comment by fasterius** [comment]
This is now added to the pipeline.
