### ISSUE TITLE
Add Docker containers

### ISSUE THREAD

**Issue by fasterius** [nf-core/spatialvi#8]
The workflow currently uses Singularity definition files, which should be converted to Docker and hosted properly on DockerHub. The Singularity images do not list specific versions for the vast majority of packages, which needs to be added. Already existing containers should be used for processes where this is applicable.

**Comment by fasterius** [comment]
Images for single-tool containers have been added, but something more advanced is needed for more complex Python (and R) environments.

**Comment by fasterius** [comment]
Temporary Docker images have been created in #17 for the more complex environments, but we should check if there is a more optimal solution.

**Comment by apeltzer** [comment]
One possibility is to actually create a mulled container for processes (multi container) via bioconda for these. Then you do not need to build and host your own. This is entirely possible with your current setup, as the recipes are already used anyways :-)
