### ISSUE TITLE
Option to use the `--unknown-slide` parameter in `spaceranger count`

### ISSUE THREAD

**Issue by pstorozenko** [nf-core/spatialvi#83]
### Description of feature

Hi!
Thanks for the work on the pipeline!
I wonder if you ever considered adding the possibility to add the [--unknown-slide](https://support.10xgenomics.com/spatial-gene-expression/software/pipelines/latest/using/slide-info) parameter to the `spaceranger count` in the spatialvi pipeline?

Current design doesn't allow for it, and expects the `slide` and `area` parameters to be always present, not allowing to work with `visium-1/2/2-large` data.

https://github.com/nf-core/spatialvi/blob/f846f0031f3b0e4fd344324cf4ef4d1404583683/modules/nf-core/spaceranger/count/main.nf#L34-L50

Best!

**Comment by fasterius** [comment]
Hi, @pstorozenko!

Sorry for the late reply, I've been on vacation. This is an issue with the `spaceranger/count` module itself, and not the `spatialvi` pipeline. I would recommend you to open an issue at the nf-core modules repository instead: https://github.com/nf-core/modules/issues. If the module is updated we can update the pipeline as well.
